repos:
    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
      hooks:
        - id: seed-isort-config
    - repo: https://github.com/timothycrosley/isort
      rev: 5.9.3
      hooks:
        - id: isort
          exclude: ^docs/

    - repo: https://github.com/psf/black
      rev: 21.9b0
      hooks:
        - id: black
          exclude: ^docs/

    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2  # pinning
      hooks:
        - id: flake8
          types:
            - python
          exclude: ^docs/

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.910'
      hooks:
      -   id: mypy
          files: jam_session_python/
